function for video extraction and subtitles
vDawgg/awt-pj-ss24-finding_scenes-2 pull request #8
Opened 2024-05-11 16:13 UTC by Rasmy000

2024-05-11 17:06 UTC, vDawgg reviewed
Unsure on state of library integration. Functionality LGTM.

2024-05-11 17:24 UTC, Rasmy000 commented on video_extraction/README.md
> +To ensure compatibility and avoid unresolved issues present in the standard version of `pytube`, it's recommended to install the library directly from the GitHub repository of the fork that contains
Gerade kriegt man einen Fehler, wenn man versucht, ein Video herunterzuladen. Sieh das hier https://github.com/pytube/pytube/issues/1918  das Format hat sich irgendwie geändert 

Und die Funktion  .generate_srt_captions() ist im master branch bei pytube auch oudatet. Daher hab ich das Projekt geforked und die Sachen gefixt. Hier siehst du was ich dann gefixt habe: https://github.com/pytube/pytube/commit/5cea63e241898a4195627d5001d13029afcceab5.

2024-05-11 17:30 UTC, Rasmy000 commented on video_extraction/README.md
> +To ensure compatibility and avoid unresolved issues present in the standard version of `pytube`, it's recommended to install the library directly from the GitHub repository of the fork that contains
https://stackoverflow.com/questions/16584552/how-to-state-in-requirements-txt-a-direct-github-source

2024-05-11 17:37 UTC, vDawgg commented on video_extraction/README.md
> +To ensure compatibility and avoid unresolved issues present in the standard version of `pytube`, it's recommended to install the library directly from the GitHub repository of the fork that contains
Ok, dann können wir das erstmal mergen und das Issue im Blick behalten. Wenn das dann upstream gefixed ist sollten wir wieder auf die eigentliche library umsteigen.
Bis zu dem punkt würde ich das aber für einfaches setup in eine requirements.txt packen:

`pytube @ git+https://github.com/Rasmy000/pytube.git`

2024-05-11 17:38 UTC, vDawgg requested changes
Put repo with fixes in requirements.txt or similar as per (comment)[https://github.com/vDawgg/awt-pj-ss24-finding_scenes-2/pull/8#discussion_r1597483414].

2024-05-12 12:09 UTC, vDawgg approved these changes
LGTM

2024-05-13 09:35 UTC, merged